services:
  panel:
    image: 'ghcr.io/pyrohost/pyrodactyl:main'
    restart: always
    ports:
      - '3000:443'
    volumes:
      - '/srv/pterodactyl/var/:/app/var/'
      - '/srv/pterodactyl/nginx/:/etc/nginx/http.d/'
      - '/srv/pterodactyl/certs/:/etc/letsencrypt/'
      - '/srv/pterodactyl/logs/:/app/storage/logs'
    environment:
      APP_ENV: production
      APP_ENVIRONMENT_ONLY: 'false'
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: 'REDIS IP ADDRESS'
      REDIS_PORT: 'REDIS PORT'
      REDIS_PASSWORD: 'REDIS PASSWORD'
      REDIS_USERNAME:
      DB_HOST: 'DATABASE IP ADDRESS'
      DB_PASSWORD: 'DATABASE PASSWORD'
      DB_PORT: 'DATABASE PORT'
      HASHIDS_LENGTH: 8
      HASHIDS_SALT: '20 CHARACTER RANDOM STRING'
      APP_URL: 'YOUR APP URL'
      APP_TIMEZONE: UTC
      APP_THEME: pterodactyl
      MAIL_DRIVER: smtp # leave all mail settings, unless you want to use mail
      MAIL_ENCRYPTION: true
      MAIL_FROM: noreply@example.com
      MAIL_HOST: mail
      MAIL_PASSWORD:
      MAIL_PORT: 1025
      MAIL_USERNAME:
